stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t mealdeliverysaas:$CI_COMMIT_SHA .
  only:
    - main
    - develop

deploy:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - docker compose -p mealdeliverysaas up --build --remove-orphans --detach
  dependencies:
    - build