services:
  web:
    build: .
    restart: unless-stopped
    container_name: mealdeliverysaas
    ports:
      - "81:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=meal-delivery-saas;Username=postgres;Password=${DB_PASSWORD:-postgres}
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: mealdeliverysaas-db
    environment:
      - POSTGRES_DB=meal-delivery-saas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: