
services:
  aspnet:
    build: .
    container_name: aspnet
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection="Server=postgres;Port=5432;Database=mealdeliverysaas;Username=postgres;Password=postgres"
  postgres:
    container_name: "postgres"
    pull_policy: always
    # https://github.com/baosystems/docker-postgis/pkgs/container/postgis
    image: ghcr.io/baosystems/postgis:18
    command: postgres -c 'max_connections=1000'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-dev-data:/var/lib/postgresql

volumes:
  postgres-dev-data: