
services:
  aspnet:
    build: .
    container_name: mealdeliverysaas
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mealdeliverysaas;Username=postgres;Password=postgres
    networks:
      - shared-db-net

networks:
  shared-db-net:
    external: true
    name: postgres
  
