-- Cleaned schema: removed autogenerated fk{n}_ columns/constraints and added real FK constraints from *_FK columns

CREATE TABLE Company(
                        Company_ID	INTEGER NOT NULL,
                        Name	VARCHAR(255) NOT NULL,
                        Slug	VARCHAR(100) NOT NULL,
                        RegistrationNumber	VARCHAR(100) NOT NULL,
                        ContactEmail	VARCHAR(255) NOT NULL,
                        ContactPhone	VARCHAR(50) NOT NULL,
                        WebSiteUrl	VARCHAR(255) NOT NULL,
                        CreatedAt	TIMESTAMP(0) NOT NULL,
                        UpdatedAt	TIMESTAMP(0),
                        DeletedAt	TIMESTAMP(0),
                        DeActivatedAt	TIMESTAMP(0),
                        CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                        CONSTRAINT	pk_Company PRIMARY KEY (Company_ID)
);

CREATE TABLE CompanySettings(
                                CompanySettings_ID	INTEGER NOT NULL,
                                DefaultNoRepeatWeeks	INTEGER NOT NULL,
                                SelectionDeadlineDaysBeforeDelivery	INTEGER NOT NULL,
                                AllowAutoSelection	BOOLEAN NOT NULL,
                                AllowPauseSubscription	BOOLEAN NOT NULL,
                                AllowSkipWeek	BOOLEAN NOT NULL,
                                MinimumSubscriptionWeeks	INTEGER NOT NULL,
                                MaxDeliveryAttempts	INTEGER NOT NULL,
                                AllowRedeliveryAfterFailure	BOOLEAN NOT NULL,
                                ComplaintEscalationThreshold	INTEGER NOT NULL,
                                ComplaintEscalationDaysWindow	INTEGER NOT NULL,
                                AutoPrioritizeFreshestStock	BOOLEAN NOT NULL,
                                AutoAssignEarliestSlot	BOOLEAN NOT NULL,
                                Company_ID_FK	INTEGER NOT NULL,
                                UpdatedAt	TIMESTAMP(0),
                                UpdatedByAppUser_ID_FK	INTEGER NOT NULL,
                                UNIQUE(Company_ID_FK),
                                CONSTRAINT	pk_CompanySettings PRIMARY KEY (CompanySettings_ID)
);

CREATE TABLE Customer(
                         Customer_ID	INTEGER NOT NULL,
                         Email	VARCHAR(255) NOT NULL,
                         FirstName	VARCHAR(100) NOT NULL,
                         LastName	VARCHAR(100) NOT NULL,
                         PhoneNumber	VARCHAR(50),
                         IsActive	BOOLEAN NOT NULL,
                         AddressLine	VARCHAR(255) NOT NULL,
                         City	VARCHAR(100) NOT NULL,
                         PostalCode	VARCHAR(20) NOT NULL,
                         Country	VARCHAR(100) NOT NULL,
                         Company_ID_FK	INTEGER NOT NULL,
                         CreatedAt	TIMESTAMP(0) NOT NULL,
                         UpdatedAt	TIMESTAMP(0),
                         DeletedAt	TIMESTAMP(0),
                         CONSTRAINT	pk_Customer PRIMARY KEY (Customer_ID)
);

CREATE TABLE MealSubscription(
                                 MealSubscription_ID	INTEGER NOT NULL,
                                 IsActive	BOOLEAN NOT NULL,
                                 StartDate	DATE NOT NULL,
                                 EndDate	DATE,
                                 AutoSelectEnabled	BOOLEAN NOT NULL,
                                 NoRepeatWeeksOverride	INTEGER,
                                 Customer_ID_FK	INTEGER NOT NULL,
                                 Box_ID_FK	INTEGER NOT NULL,
                                 CreatedAt	TIMESTAMP(0) NOT NULL,
                                 UpdatedAt	TIMESTAMP(0),
                                 DeletedAt	TIMESTAMP(0),
                                 CONSTRAINT	pk_MealSubscription PRIMARY KEY (MealSubscription_ID)
);

CREATE TABLE DeliveryZone(
                             DeliveryZone_ID	INTEGER NOT NULL,
                             Name	VARCHAR(150) NOT NULL,
                             Description	VARCHAR(250),
                             IsActive	BOOLEAN NOT NULL,
                             Company_ID_FK	INTEGER NOT NULL,
                             CreatedAt	TIMESTAMP(0) NOT NULL,
                             UpdatedAt	TIMESTAMP(0),
                             DeletedAt	TIMESTAMP(0),
                             CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                             CONSTRAINT	pk_DeliveryZone PRIMARY KEY (DeliveryZone_ID)
);

CREATE TABLE Recipe(
                       Recipe_ID	INTEGER NOT NULL,
                       Name	VARCHAR(200) NOT NULL,
                       Description	TEXT,
                       ImageUrl	VARCHAR(500),
                       DefaultServings	INTEGER NOT NULL,
                       IsActive	BOOLEAN NOT NULL,
                       Company_ID_FK	INTEGER NOT NULL,
                       CreatedAt	TIMESTAMP(0) NOT NULL,
                       UpdatedAt	TIMESTAMP(0),
                       DeletedAt	TIMESTAMP(0),
                       CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                       CONSTRAINT	pk_Recipe PRIMARY KEY (Recipe_ID)
);

CREATE TABLE RecipeIngredient(
                                 RecipeIngredient_ID	INTEGER NOT NULL,
                                 Recipe_ID_FK	INTEGER NOT NULL,
                                 Ingredient_ID_FK	INTEGER NOT NULL,
                                 CreatedAt	TIMESTAMP(0) NOT NULL,
                                 DeletedAt	TIMESTAMP(0),
                                 CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                                 CONSTRAINT	pk_RecipeIngredient PRIMARY KEY (RecipeIngredient_ID)
);

CREATE TABLE Ingredient(
                           Ingredient_ID	INTEGER NOT NULL,
                           Name	VARCHAR(150) NOT NULL,
                           Company_ID_FK	INTEGER NOT NULL,
                           CreatedAt	TIMESTAMP(0) NOT NULL,
                           UpdatedAt	TIMESTAMP(0),
                           DeletedAt	TIMESTAMP(0),
                           CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                           CONSTRAINT	pk_Ingredient PRIMARY KEY (Ingredient_ID)
);

CREATE TABLE NutritionalInfo(
                                NutritionalInfo_ID	INTEGER NOT NULL,
                                CaloriesKcal	NUMERIC(7,2) NOT NULL,
                                ProteinG	NUMERIC(7,2) NOT NULL,
                                CarbsG	NUMERIC(7,2) NOT NULL,
                                FatG	NUMERIC(7,2) NOT NULL,
                                FiberG	NUMERIC(7,2) NOT NULL,
                                SodiumMg	NUMERIC(9,2) NOT NULL,
                                SugarG	NUMERIC(7,2) NOT NULL,
                                SaturatedFatG	NUMERIC(7,2) NOT NULL,
                                Recipe_ID_FK	INTEGER NOT NULL,
                                CreatedAt	TIMESTAMP(0) NOT NULL,
                                UpdatedAt	TIMESTAMP(0),
                                CONSTRAINT	pk_NutritionalInfo PRIMARY KEY (NutritionalInfo_ID)
);

CREATE TABLE WeeklyMenu(
                           WeeklyMenu_ID	INTEGER NOT NULL,
                           WeekStartDate	DATE NOT NULL,
                           SelectionDeadlineAt	TIMESTAMP(0) NOT NULL,
                           TotalRecipes	INTEGER NOT NULL,
                           IsPublished	BOOLEAN NOT NULL,
                           PublishedAt	TIMESTAMP(0) NOT NULL,
                           Company_ID_FK	INTEGER NOT NULL,
                           CreatedAt	TIMESTAMP(0),
                           UpdatedAt	TIMESTAMP(0),
                           DeletedAt	TIMESTAMP(0),
                           CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                           CONSTRAINT	pk_WeeklyMenu PRIMARY KEY (WeeklyMenu_ID)
);

CREATE TABLE MealSelection(
                              MealSelection_ID	INTEGER NOT NULL,
                              SelectedAutomatically	BOOLEAN NOT NULL,
                              SelectedAt	TIMESTAMP(0) NOT NULL,
                              LockedAt	TIMESTAMP(0),
                              CreatedAt	TIMESTAMP(0) NOT NULL,
                              UpdatedAt	TIMESTAMP(0),
                              DeletedAt	TIMESTAMP(0),
                              MealSubscription_ID_FK	INTEGER NOT NULL,
                              WeeklyMenu_ID_FK	INTEGER NOT NULL,
                              Recipe_ID_FK	INTEGER NOT NULL,
                              CONSTRAINT	pk_MealSelection PRIMARY KEY (MealSelection_ID)
);

CREATE TABLE Delivery(
                         Delivery_ID	INTEGER NOT NULL,
                         ScheduledTime	TIMESTAMP(0) NOT NULL,
                         DeliveredAt	TIMESTAMP(0),
                         FailureReason	VARCHAR(255),
                         AddressLine	VARCHAR(255) NOT NULL,
                         City	VARCHAR(100) NOT NULL,
                         PostalCode	VARCHAR(20) NOT NULL,
                         Country	VARCHAR(100) NOT NULL,
                         DeliveryStatus_ID_FK	INTEGER NOT NULL,
                         Company_ID_FK	INTEGER NOT NULL,
                         Customer_ID_FK	INTEGER NOT NULL,
                         WeeklyMenu_ID_FK	INTEGER NOT NULL,
                         DeliveryZone_ID_FK	INTEGER NOT NULL,
                         DeliveryWindow_ID_FK	INTEGER NOT NULL,
                         Box_ID_FK	INTEGER NOT NULL,
                         MealSelection_ID_FK	INTEGER NOT NULL,
                         MealSubscription_ID_FK	INTEGER NOT NULL,
                         CreatedAt	TIMESTAMP(0) NOT NULL,
                         UpdatedAt	TIMESTAMP(0),
                         DeletedAt	TIMESTAMP(0),
                         CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                         CONSTRAINT	pk_Delivery PRIMARY KEY (Delivery_ID)
);

CREATE TABLE DeliveryAttempt(
                                DeliveryAttempt_ID	INTEGER NOT NULL,
                                AttemptNo	INTEGER NOT NULL,
                                AttemptAt	TIMESTAMP(0) NOT NULL,
                                Notes	TEXT NOT NULL,
                                DeliveryAttemptResult_ID_FK	INTEGER NOT NULL,
                                Delivery_ID_FK	INTEGER NOT NULL,
                                CreatedAt	TIMESTAMP(0) NOT NULL,
                                UpdatedAt	TIMESTAMP(0),
                                DeletedAt	TIMESTAMP(0),
                                CONSTRAINT	pk_DeliveryAttempt PRIMARY KEY (DeliveryAttempt_ID)
);

CREATE TABLE Rating(
                       Rating_ID	INTEGER NOT NULL,
                       Score	INTEGER NOT NULL,
                       RatedAt	TIMESTAMP(0) NOT NULL,
                       Notes	VARCHAR(500) NOT NULL,
                       Customer_ID_FK	INTEGER NOT NULL,
                       RECIPE_ID_FK	INTEGER NOT NULL,
                       DeletedAt	TIMESTAMP(0),
                       UpdatedAt	TIMESTAMP(0),
                       CONSTRAINT	pk_Rating PRIMARY KEY (Rating_ID)
);

CREATE TABLE CustomerExclusion(
                                  CustomerExclusion_ID	INTEGER NOT NULL,
                                  Ingredient_ID_FK	INTEGER NOT NULL,
                                  Customer_ID_FK	INTEGER NOT NULL,
                                  CreatedAt	TIMESTAMP(0) NOT NULL,
                                  DeletedAt	TIMESTAMP(0),
                                  CONSTRAINT	pk_CustomerExclusion PRIMARY KEY (CustomerExclusion_ID)
);

CREATE TABLE Box(
                    Box_ID	INTEGER NOT NULL,
                    MealsCount	INTEGER NOT NULL,
                    PeopleCount	INTEGER NOT NULL,
                    DisplayName	VARCHAR(100) NOT NULL,
                    IsActive	BOOLEAN NOT NULL,
                    CreatedAt	TIMESTAMP(0) NOT NULL,
                    UpdatedAt	TIMESTAMP(0),
                    DeletedAt	TIMESTAMP(0),
                    CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                    Company_ID_FK	INTEGER NOT NULL,
                    CONSTRAINT	pk_Box PRIMARY KEY (Box_ID)
);

CREATE TABLE PlatformSubscription(
                                     PlatformSubscription_ID	INTEGER NOT NULL,
                                     ValidFrom	DATE NOT NULL,
                                     ValidTo	DATE,
                                     Company_ID_FK	INTEGER NOT NULL,
                                     PlatformSubscriptionTier_ID_FK	INTEGER NOT NULL,
                                     PlatformSubscriptionStatus_ID_FK	INTEGER NOT NULL,
                                     CreatedAt	TIMESTAMP(0) NOT NULL,
                                     UpdatedAt	TIMESTAMP(0),
                                     DeletedAt	TIMESTAMP(0),
                                     CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                                     CONSTRAINT	pk_PlatformSubscription PRIMARY KEY (PlatformSubscription_ID)
);

CREATE TABLE AppUser(
                        AppUser_ID	INTEGER NOT NULL,
                        FirstName	VARCHAR(100) NOT NULL,
                        LastName	VARCHAR(100) NOT NULL,
                        IsDeleted	BOOLEAN NOT NULL,
                        CreatedAt	TIMESTAMP(0) NOT NULL,
                        UpdatedAt	TIMESTAMP(0),
                        DeletedAt	TIMESTAMP(0),
                        IdentityUser_ID_FK	INTEGER NOT NULL,
                        UNIQUE(IdentityUser_ID_FK),
                        CONSTRAINT	pk_AppUser PRIMARY KEY (AppUser_ID)
);

CREATE TABLE CompanyAppUser(
                               CompanyAppUser_ID	INTEGER NOT NULL,
                               IsOwner	BOOLEAN NOT NULL,
                               IsActive	BOOLEAN NOT NULL,
                               Company_ID_FK	INTEGER NOT NULL,
                               AppUser_ID_FK	INTEGER NOT NULL,
                               CompanyRole_ID_FK	INTEGER NOT NULL,
                               CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                               CreatedAt	TIMESTAMP(0) NOT NULL,
                               UpdatedAt	TIMESTAMP(0),
                               DeletedAt	TIMESTAMP(0),
                               CONSTRAINT	pk_CompanyAppUser PRIMARY KEY (CompanyAppUser_ID)
);

CREATE TABLE DietaryCategory(
                                DietaryCategory_ID	INTEGER NOT NULL,
                                Code	VARCHAR(50) NOT NULL,
                                Name	VARCHAR(100) NOT NULL,
                                IsActive	BOOLEAN NOT NULL,
                                Company_ID_FK	INTEGER NOT NULL,
                                CreatedAt	TIMESTAMP(0) NOT NULL,
                                UpdatedAt	TIMESTAMP(0),
                                DeletedAt	TIMESTAMP(0),
                                CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                                CONSTRAINT	pk_DietaryCategory PRIMARY KEY (DietaryCategory_ID)
);

CREATE TABLE RecipeDietaryCategory(
                                      RecipeDietaryCategory_ID	INTEGER NOT NULL,
                                      DietaryCategory_ID_FK	INTEGER NOT NULL,
                                      Recipe_ID_FK	INTEGER NOT NULL,
                                      CreatedAt	TIMESTAMP(0) NOT NULL,
                                      DeletedAt	TIMESTAMP(0),
                                      CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                                      CONSTRAINT	pk_RecipeDietaryCategory PRIMARY KEY (RecipeDietaryCategory_ID)
);

CREATE TABLE WeeklyMenuRecipe(
                                 WeeklyMenuRecipe_ID	INTEGER NOT NULL,
                                 Recipe_ID_FK	INTEGER NOT NULL,
                                 WeeklyMenu_ID_FK	INTEGER NOT NULL,
                                 DisplayOrder	INTEGER,
                                 IsFeatured	BOOLEAN NOT NULL,
                                 CreatedAt	TIMESTAMP(0) NOT NULL,
                                 DeletedAt	TIMESTAMP(0),
                                 CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                                 CONSTRAINT	pk_WeeklyMenuRecipe PRIMARY KEY (WeeklyMenuRecipe_ID)
);

CREATE TABLE DeliveryWindow(
                               DeliveryWindow_ID	INTEGER NOT NULL,
                               DayOfWeek	INTEGER NOT NULL,
                               StartTime	TIME(0) NOT NULL,
                               EndTime	TIME(0) NOT NULL,
                               Capacity	INTEGER,
                               IsActive	BOOLEAN NOT NULL,
                               DeliveryZone_ID_FK	INTEGER NOT NULL,
                               CreatedAt	TIMESTAMP(0) NOT NULL,
                               UpdatedAt	TIMESTAMP(0),
                               DeletedAt	TIMESTAMP(0),
                               CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                               CONSTRAINT	pk_DeliveryWindow PRIMARY KEY (DeliveryWindow_ID)
);

CREATE TABLE QualityComplaint(
                                 QualityComplaint_ID	INTEGER NOT NULL,
                                 Severity	INTEGER NOT NULL,
                                 Description	TEXT NOT NULL,
                                 EscalatedAt	TIMESTAMP(0),
                                 EscalationAction	VARCHAR(255),
                                 Company_ID_FK	INTEGER NOT NULL,
                                 Customer_ID_FK	INTEGER NOT NULL,
                                 Delivery_ID_FK	INTEGER NOT NULL,
                                 QualityComplaintType_ID_FK	INTEGER NOT NULL,
                                 QualityComplaintStatus_ID_FK	INTEGER NOT NULL,
                                 CreatedAt	TIMESTAMP(0) NOT NULL,
                                 UpdatedAt	TIMESTAMP(0),
                                 DeletedAt	TIMESTAMP(0),
                                 CONSTRAINT	pk_QualityComplaint PRIMARY KEY (QualityComplaint_ID)
);

CREATE TABLE CompanyRole(
                            CompanyRole_ID	INTEGER NOT NULL,
                            Code	VARCHAR(100) NOT NULL UNIQUE,
                            Label	VARCHAR(255) NOT NULL,
                            CONSTRAINT	pk_CompanyRole PRIMARY KEY (CompanyRole_ID)
);

CREATE TABLE PlatformSubscriptionTier(
                                         PlatformSubscriptionTier_ID	INTEGER NOT NULL,
                                         Code	VARCHAR(100) NOT NULL UNIQUE,
                                         Name	VARCHAR(255) NOT NULL,
                                         MaxZones	INTEGER NOT NULL,
                                         MaxSubscribers	INTEGER NOT NULL,
                                         MaxEmployees	INTEGER NOT NULL,
                                         MaxRecipes	INTEGER NOT NULL,
                                         IsActive	BOOLEAN NOT NULL,
                                         CreatedAt	TIMESTAMP(0) NOT NULL,
                                         UpdatedAt	TIMESTAMP(0),
                                         DeletedAt	TIMESTAMP(0),
                                         CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                                         CONSTRAINT	pk_PlatformSubscriptionTier PRIMARY KEY (PlatformSubscriptionTier_ID)
);

CREATE TABLE PlatformSubscriptionStatus(
                                           PlatformSubscriptionStatus_ID	INTEGER NOT NULL,
                                           Code	VARCHAR(100) NOT NULL UNIQUE,
                                           Label	VARCHAR(255) NOT NULL,
                                           CONSTRAINT	pk_PlatformSubscriptionStatus PRIMARY KEY (PlatformSubscriptionStatus_ID)
);

CREATE TABLE IdentityUser(
                             IdentityUser_ID	INTEGER NOT NULL,
                             CONSTRAINT	pk_IdentityUser PRIMARY KEY (IdentityUser_ID)
);

CREATE TABLE BoxPrice(
                         BoxPrice_ID	INTEGER NOT NULL,
                         PriceAmount	NUMERIC(12,2) NOT NULL,
                         ValidFrom	DATE,
                         ValidTo	DATE,
                         IsActive	BOOLEAN NOT NULL,
                         Box_ID_FK	INTEGER NOT NULL,
                         Company_ID_FK	INTEGER NOT NULL,
                         CreatedAt	TIMESTAMP(0) NOT NULL,
                         UpdatedAt	TIMESTAMP(0),
                         DeletedAt	TIMESTAMP(0),
                         CreatedByAppUser_ID_FK	INTEGER NOT NULL,
                         CONSTRAINT	pk_BoxPrice PRIMARY KEY (BoxPrice_ID)
);

CREATE TABLE CustomerPreference(
                                   CustomerPreference_ID	INTEGER NOT NULL,
                                   DietaryCategory_ID_FK	INTEGER NOT NULL,
                                   Customer_ID_FK	INTEGER NOT NULL,
                                   CreatedAt	TIMESTAMP(0) NOT NULL,
                                   DeletedAt	TIMESTAMP(0),
                                   CONSTRAINT	pk_CustomerPreference PRIMARY KEY (CustomerPreference_ID)
);

CREATE TABLE CustomerAppUser(
                                CustomerAppUser_ID	INTEGER NOT NULL,
                                Customer_ID_FK	INTEGER NOT NULL,
                                AppUser_ID_FK	INTEGER NOT NULL,
                                CreatedAt	TIMESTAMP(0) NOT NULL,
                                DeletedAt	TIMESTAMP(0),
                                CONSTRAINT	pk_CustomerAppUser PRIMARY KEY (CustomerAppUser_ID)
);

CREATE TABLE DeliveryStatus(
                               DeliveryStatus_ID	INTEGER NOT NULL,
                               Code	VARCHAR(100) NOT NULL UNIQUE,
                               Label	VARCHAR(100) NOT NULL,
                               CONSTRAINT	pk_DeliveryStatus PRIMARY KEY (DeliveryStatus_ID)
);

CREATE TABLE DeliveryAttemptResult(
                                      DeliveryAttemptResult_ID	INTEGER NOT NULL,
                                      Code	VARCHAR(100) NOT NULL UNIQUE,
                                      Label	VARCHAR(100) NOT NULL,
                                      CONSTRAINT	pk_DeliveryAttemptResult PRIMARY KEY (DeliveryAttemptResult_ID)
);

CREATE TABLE QualityComplaintType(
                                     QualityComplaintType_ID	INTEGER NOT NULL,
                                     Code	VARCHAR(100) NOT NULL UNIQUE,
                                     Label	VARCHAR(100) NOT NULL,
                                     CONSTRAINT	pk_QualityComplaintType PRIMARY KEY (QualityComplaintType_ID)
);

CREATE TABLE QualityComplaintStatus(
                                       QualityComplaintStatus_ID	INTEGER NOT NULL,
                                       Code	VARCHAR(100) NOT NULL UNIQUE,
                                       Label	VARCHAR(100) NOT NULL,
                                       CONSTRAINT	pk_QualityComplaintStatus PRIMARY KEY (QualityComplaintStatus_ID)
);

-- Foreign key constraints
ALTER TABLE Company
    ADD CONSTRAINT fk_Company_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CompanySettings
    ADD CONSTRAINT fk_CompanySettings_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CompanySettings
    ADD CONSTRAINT fk_CompanySettings_UpdatedByAppUser_ID_FK FOREIGN KEY (UpdatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Customer
    ADD CONSTRAINT fk_Customer_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MealSubscription
    ADD CONSTRAINT fk_MealSubscription_Customer_ID_FK FOREIGN KEY (Customer_ID_FK)
        REFERENCES Customer(Customer_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MealSubscription
    ADD CONSTRAINT fk_MealSubscription_Box_ID_FK FOREIGN KEY (Box_ID_FK)
        REFERENCES Box(Box_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DeliveryZone
    ADD CONSTRAINT fk_DeliveryZone_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DeliveryZone
    ADD CONSTRAINT fk_DeliveryZone_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Recipe
    ADD CONSTRAINT fk_Recipe_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Recipe
    ADD CONSTRAINT fk_Recipe_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RecipeIngredient
    ADD CONSTRAINT fk_RecipeIngredient_Recipe_ID_FK FOREIGN KEY (Recipe_ID_FK)
        REFERENCES Recipe(Recipe_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RecipeIngredient
    ADD CONSTRAINT fk_RecipeIngredient_Ingredient_ID_FK FOREIGN KEY (Ingredient_ID_FK)
        REFERENCES Ingredient(Ingredient_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RecipeIngredient
    ADD CONSTRAINT fk_RecipeIngredient_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Ingredient
    ADD CONSTRAINT fk_Ingredient_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Ingredient
    ADD CONSTRAINT fk_Ingredient_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE NutritionalInfo
    ADD CONSTRAINT fk_NutritionalInfo_Recipe_ID_FK FOREIGN KEY (Recipe_ID_FK)
        REFERENCES Recipe(Recipe_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE WeeklyMenu
    ADD CONSTRAINT fk_WeeklyMenu_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE WeeklyMenu
    ADD CONSTRAINT fk_WeeklyMenu_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MealSelection
    ADD CONSTRAINT fk_MealSelection_MealSubscription_ID_FK FOREIGN KEY (MealSubscription_ID_FK)
        REFERENCES MealSubscription(MealSubscription_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MealSelection
    ADD CONSTRAINT fk_MealSelection_WeeklyMenu_ID_FK FOREIGN KEY (WeeklyMenu_ID_FK)
        REFERENCES WeeklyMenu(WeeklyMenu_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MealSelection
    ADD CONSTRAINT fk_MealSelection_Recipe_ID_FK FOREIGN KEY (Recipe_ID_FK)
        REFERENCES Recipe(Recipe_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Delivery
    ADD CONSTRAINT fk_Delivery_DeliveryStatus_ID_FK FOREIGN KEY (DeliveryStatus_ID_FK)
        REFERENCES DeliveryStatus(DeliveryStatus_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Delivery
    ADD CONSTRAINT fk_Delivery_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Delivery
    ADD CONSTRAINT fk_Delivery_Customer_ID_FK FOREIGN KEY (Customer_ID_FK)
        REFERENCES Customer(Customer_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Delivery
    ADD CONSTRAINT fk_Delivery_WeeklyMenu_ID_FK FOREIGN KEY (WeeklyMenu_ID_FK)
        REFERENCES WeeklyMenu(WeeklyMenu_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Delivery
    ADD CONSTRAINT fk_Delivery_DeliveryZone_ID_FK FOREIGN KEY (DeliveryZone_ID_FK)
        REFERENCES DeliveryZone(DeliveryZone_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Delivery
    ADD CONSTRAINT fk_Delivery_DeliveryWindow_ID_FK FOREIGN KEY (DeliveryWindow_ID_FK)
        REFERENCES DeliveryWindow(DeliveryWindow_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Delivery
    ADD CONSTRAINT fk_Delivery_Box_ID_FK FOREIGN KEY (Box_ID_FK)
        REFERENCES Box(Box_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Delivery
    ADD CONSTRAINT fk_Delivery_MealSelection_ID_FK FOREIGN KEY (MealSelection_ID_FK)
        REFERENCES MealSelection(MealSelection_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Delivery
    ADD CONSTRAINT fk_Delivery_MealSubscription_ID_FK FOREIGN KEY (MealSubscription_ID_FK)
        REFERENCES MealSubscription(MealSubscription_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Delivery
    ADD CONSTRAINT fk_Delivery_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DeliveryAttempt
    ADD CONSTRAINT fk_DeliveryAttempt_DeliveryAttemptResult_ID_FK FOREIGN KEY (DeliveryAttemptResult_ID_FK)
        REFERENCES DeliveryAttemptResult(DeliveryAttemptResult_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DeliveryAttempt
    ADD CONSTRAINT fk_DeliveryAttempt_Delivery_ID_FK FOREIGN KEY (Delivery_ID_FK)
        REFERENCES Delivery(Delivery_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Rating
    ADD CONSTRAINT fk_Rating_Customer_ID_FK FOREIGN KEY (Customer_ID_FK)
        REFERENCES Customer(Customer_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Rating
    ADD CONSTRAINT fk_Rating_RECIPE_ID_FK FOREIGN KEY (RECIPE_ID_FK)
        REFERENCES Recipe(Recipe_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CustomerExclusion
    ADD CONSTRAINT fk_CustomerExclusion_Ingredient_ID_FK FOREIGN KEY (Ingredient_ID_FK)
        REFERENCES Ingredient(Ingredient_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CustomerExclusion
    ADD CONSTRAINT fk_CustomerExclusion_Customer_ID_FK FOREIGN KEY (Customer_ID_FK)
        REFERENCES Customer(Customer_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Box
    ADD CONSTRAINT fk_Box_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Box
    ADD CONSTRAINT fk_Box_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PlatformSubscription
    ADD CONSTRAINT fk_PlatformSubscription_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PlatformSubscription
    ADD CONSTRAINT fk_PlatformSubscription_PlatformSubscriptionTier_ID_FK FOREIGN KEY (PlatformSubscriptionTier_ID_FK)
        REFERENCES PlatformSubscriptionTier(PlatformSubscriptionTier_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PlatformSubscription
    ADD CONSTRAINT fk_PlatformSubscription_PlatformSubscriptionStatus_ID_FK FOREIGN KEY (PlatformSubscriptionStatus_ID_FK)
        REFERENCES PlatformSubscriptionStatus(PlatformSubscriptionStatus_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PlatformSubscription
    ADD CONSTRAINT fk_PlatformSubscription_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CompanyAppUser
    ADD CONSTRAINT fk_CompanyAppUser_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CompanyAppUser
    ADD CONSTRAINT fk_CompanyAppUser_AppUser_ID_FK FOREIGN KEY (AppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CompanyAppUser
    ADD CONSTRAINT fk_CompanyAppUser_CompanyRole_ID_FK FOREIGN KEY (CompanyRole_ID_FK)
        REFERENCES CompanyRole(CompanyRole_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CompanyAppUser
    ADD CONSTRAINT fk_CompanyAppUser_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DietaryCategory
    ADD CONSTRAINT fk_DietaryCategory_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DietaryCategory
    ADD CONSTRAINT fk_DietaryCategory_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RecipeDietaryCategory
    ADD CONSTRAINT fk_RecipeDietaryCategory_DietaryCategory_ID_FK FOREIGN KEY (DietaryCategory_ID_FK)
        REFERENCES DietaryCategory(DietaryCategory_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RecipeDietaryCategory
    ADD CONSTRAINT fk_RecipeDietaryCategory_Recipe_ID_FK FOREIGN KEY (Recipe_ID_FK)
        REFERENCES Recipe(Recipe_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RecipeDietaryCategory
    ADD CONSTRAINT fk_RecipeDietaryCategory_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE WeeklyMenuRecipe
    ADD CONSTRAINT fk_WeeklyMenuRecipe_Recipe_ID_FK FOREIGN KEY (Recipe_ID_FK)
        REFERENCES Recipe(Recipe_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE WeeklyMenuRecipe
    ADD CONSTRAINT fk_WeeklyMenuRecipe_WeeklyMenu_ID_FK FOREIGN KEY (WeeklyMenu_ID_FK)
        REFERENCES WeeklyMenu(WeeklyMenu_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE WeeklyMenuRecipe
    ADD CONSTRAINT fk_WeeklyMenuRecipe_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DeliveryWindow
    ADD CONSTRAINT fk_DeliveryWindow_DeliveryZone_ID_FK FOREIGN KEY (DeliveryZone_ID_FK)
        REFERENCES DeliveryZone(DeliveryZone_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DeliveryWindow
    ADD CONSTRAINT fk_DeliveryWindow_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE QualityComplaint
    ADD CONSTRAINT fk_QualityComplaint_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE QualityComplaint
    ADD CONSTRAINT fk_QualityComplaint_Customer_ID_FK FOREIGN KEY (Customer_ID_FK)
        REFERENCES Customer(Customer_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE QualityComplaint
    ADD CONSTRAINT fk_QualityComplaint_Delivery_ID_FK FOREIGN KEY (Delivery_ID_FK)
        REFERENCES Delivery(Delivery_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE QualityComplaint
    ADD CONSTRAINT fk_QualityComplaint_QualityComplaintType_ID_FK FOREIGN KEY (QualityComplaintType_ID_FK)
        REFERENCES QualityComplaintType(QualityComplaintType_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE QualityComplaint
    ADD CONSTRAINT fk_QualityComplaint_QualityComplaintStatus_ID_FK FOREIGN KEY (QualityComplaintStatus_ID_FK)
        REFERENCES QualityComplaintStatus(QualityComplaintStatus_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PlatformSubscriptionTier
    ADD CONSTRAINT fk_PlatformSubscriptionTier_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BoxPrice
    ADD CONSTRAINT fk_BoxPrice_Box_ID_FK FOREIGN KEY (Box_ID_FK)
        REFERENCES Box(Box_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BoxPrice
    ADD CONSTRAINT fk_BoxPrice_Company_ID_FK FOREIGN KEY (Company_ID_FK)
        REFERENCES Company(Company_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BoxPrice
    ADD CONSTRAINT fk_BoxPrice_CreatedByAppUser_ID_FK FOREIGN KEY (CreatedByAppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CustomerPreference
    ADD CONSTRAINT fk_CustomerPreference_DietaryCategory_ID_FK FOREIGN KEY (DietaryCategory_ID_FK)
        REFERENCES DietaryCategory(DietaryCategory_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CustomerPreference
    ADD CONSTRAINT fk_CustomerPreference_Customer_ID_FK FOREIGN KEY (Customer_ID_FK)
        REFERENCES Customer(Customer_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CustomerAppUser
    ADD CONSTRAINT fk_CustomerAppUser_Customer_ID_FK FOREIGN KEY (Customer_ID_FK)
        REFERENCES Customer(Customer_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CustomerAppUser
    ADD CONSTRAINT fk_CustomerAppUser_AppUser_ID_FK FOREIGN KEY (AppUser_ID_FK)
        REFERENCES AppUser(AppUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;


-- Additional FK constraints (PostgreSQL)
ALTER TABLE AppUser
    ADD CONSTRAINT fk_AppUser_IdentityUser_ID_FK FOREIGN KEY (IdentityUser_ID_FK)
        REFERENCES IdentityUser(IdentityUser_ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT;


-- Indexes (PostgreSQL)
CREATE UNIQUE INDEX ux_company_slug ON Company (Slug);
CREATE UNIQUE INDEX ux_companysettings_company ON CompanySettings (Company_ID_FK);
CREATE UNIQUE INDEX ux_customer_company_email ON Customer (Company_ID_FK, Email) WHERE DeletedAt IS NULL;
CREATE UNIQUE INDEX ux_box_company_meals_people ON Box (Company_ID_FK, MealsCount, PeopleCount) WHERE DeletedAt IS NULL;
CREATE UNIQUE INDEX ux_dietarycategory_company_code ON DietaryCategory (Company_ID_FK, Code) WHERE DeletedAt IS NULL;
CREATE UNIQUE INDEX ux_nutritionalinfo_recipe ON NutritionalInfo (Recipe_ID_FK);
CREATE UNIQUE INDEX ux_weeklymenu_company_weekstart ON WeeklyMenu (Company_ID_FK, WeekStartDate) WHERE DeletedAt IS NULL;
CREATE UNIQUE INDEX ux_companyappuser_company_user ON CompanyAppUser (Company_ID_FK, AppUser_ID_FK) WHERE DeletedAt IS NULL;
CREATE UNIQUE INDEX ux_customereclusion_customer_ingredient ON CustomerExclusion (Customer_ID_FK, Ingredient_ID_FK) WHERE DeletedAt IS NULL;
CREATE UNIQUE INDEX ux_recipient_menu_recipe ON WeeklyMenuRecipe (WeeklyMenu_ID_FK, Recipe_ID_FK) WHERE DeletedAt IS NULL;
CREATE UNIQUE INDEX ux_mealselection_sub_menu_recipe ON MealSelection (MealSubscription_ID_FK, WeeklyMenu_ID_FK, Recipe_ID_FK) WHERE DeletedAt IS NULL;
CREATE UNIQUE INDEX ux_platformsubscription_company_active ON PlatformSubscription (Company_ID_FK) WHERE DeletedAt IS NULL;
CREATE INDEX ux_boxprice_company_box_active ON BoxPrice (Company_ID_FK, Box_ID_FK);
CREATE INDEX ix_company_createdby ON Company (CreatedByAppUser_ID_FK);
CREATE INDEX ix_companysettings_updatedby ON CompanySettings (UpdatedByAppUser_ID_FK);
CREATE INDEX ix_customer_company ON Customer (Company_ID_FK);
CREATE INDEX ix_mealsub_customer ON MealSubscription (Customer_ID_FK);
CREATE INDEX ix_mealsub_box ON MealSubscription (Box_ID_FK);
CREATE INDEX ix_deliveryzone_company ON DeliveryZone (Company_ID_FK);
CREATE INDEX ix_recipe_company ON Recipe (Company_ID_FK);
CREATE INDEX ix_recipeingredient_recipe ON RecipeIngredient (Recipe_ID_FK);
CREATE INDEX ix_recipeingredient_ingredient ON RecipeIngredient (Ingredient_ID_FK);
CREATE INDEX ix_ingredient_company ON Ingredient (Company_ID_FK);
CREATE INDEX ix_weeklymenu_company ON WeeklyMenu (Company_ID_FK);
CREATE INDEX ix_weeklymenurecipe_weeklymenu ON WeeklyMenuRecipe (WeeklyMenu_ID_FK);
CREATE INDEX ix_mealselection_weeklymenu ON MealSelection (WeeklyMenu_ID_FK);
CREATE INDEX ix_mealselection_recipe ON MealSelection (Recipe_ID_FK);
CREATE INDEX ix_delivery_company_scheduled ON Delivery (Company_ID_FK, ScheduledTime);
CREATE INDEX ix_delivery_customer ON Delivery (Customer_ID_FK);
CREATE INDEX ix_delivery_weeklymenu ON Delivery (WeeklyMenu_ID_FK);
CREATE INDEX ix_delivery_zone ON Delivery (DeliveryZone_ID_FK);
CREATE INDEX ix_delivery_window ON Delivery (DeliveryWindow_ID_FK);
CREATE INDEX ix_delivery_mealsub ON Delivery (MealSubscription_ID_FK);
CREATE INDEX ix_deliveryattempt_delivery ON DeliveryAttempt (Delivery_ID_FK);
CREATE INDEX ix_rating_customer ON Rating (Customer_ID_FK);
CREATE INDEX ix_rating_recipe ON Rating (RECIPE_ID_FK);
CREATE INDEX ix_deliverywindow_zone_day ON DeliveryWindow (DeliveryZone_ID_FK, DayOfWeek);
CREATE INDEX ix_qualitycomplaint_customer_created ON QualityComplaint (Customer_ID_FK, CreatedAt);
CREATE INDEX ix_qualitycomplaint_company_created ON QualityComplaint (Company_ID_FK, CreatedAt);


-- ============================================================
-- Added defaults and CHECK constraints (generated patch)
-- ============================================================

-- Default timestamps for CreatedAt
ALTER TABLE AppUser ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Box ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE BoxPrice ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Company ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE CompanyAppUser ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Customer ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE CustomerAppUser ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE CustomerExclusion ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE CustomerPreference ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Delivery ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE DeliveryAttempt ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE DeliveryWindow ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE DeliveryZone ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE DietaryCategory ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Ingredient ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE MealSelection ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE MealSubscription ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE NutritionalInfo ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE PlatformSubscription ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE PlatformSubscriptionTier ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE QualityComplaint ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Recipe ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE RecipeDietaryCategory ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE RecipeIngredient ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE WeeklyMenu ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE WeeklyMenuRecipe ALTER COLUMN CreatedAt SET DEFAULT CURRENT_TIMESTAMP;

-- CompanySettings defaults
ALTER TABLE CompanySettings ALTER COLUMN DefaultNoRepeatWeeks SET DEFAULT 8;
ALTER TABLE CompanySettings ALTER COLUMN SelectionDeadlineDaysBeforeDelivery SET DEFAULT 3;
ALTER TABLE CompanySettings ALTER COLUMN AllowAutoSelection SET DEFAULT TRUE;
ALTER TABLE CompanySettings ALTER COLUMN AllowPauseSubscription SET DEFAULT TRUE;
ALTER TABLE CompanySettings ALTER COLUMN AllowSkipWeek SET DEFAULT TRUE;
ALTER TABLE CompanySettings ALTER COLUMN MinimumSubscriptionWeeks SET DEFAULT 0;
ALTER TABLE CompanySettings ALTER COLUMN MaxDeliveryAttempts SET DEFAULT 2;
ALTER TABLE CompanySettings ALTER COLUMN AllowRedeliveryAfterFailure SET DEFAULT TRUE;
ALTER TABLE CompanySettings ALTER COLUMN ComplaintEscalationThreshold SET DEFAULT 2;
ALTER TABLE CompanySettings ALTER COLUMN ComplaintEscalationDaysWindow SET DEFAULT 30;
ALTER TABLE CompanySettings ALTER COLUMN AutoPrioritizeFreshestStock SET DEFAULT TRUE;
ALTER TABLE CompanySettings ALTER COLUMN AutoAssignEarliestSlot SET DEFAULT FALSE;

-- Box constraints (meals/people)
ALTER TABLE Box ADD CONSTRAINT ck_Box_MealsCount CHECK (MealsCount IN (3,4,5));
ALTER TABLE Box ADD CONSTRAINT ck_Box_PeopleCount CHECK (PeopleCount IN (2,4));

-- Rating score constraint
ALTER TABLE Rating ADD CONSTRAINT ck_Rating_Score CHECK (Score BETWEEN 1 AND 5);

-- Delivery window validity constraints
ALTER TABLE DeliveryWindow ADD CONSTRAINT ck_DeliveryWindow_DayOfWeek CHECK (DayOfWeek BETWEEN 1 AND 7);
ALTER TABLE DeliveryWindow ADD CONSTRAINT ck_DeliveryWindow_TimeRange CHECK (StartTime < EndTime);

-- NutritionalInfo non-negative constraints (per serving)
ALTER TABLE NutritionalInfo
    ADD CONSTRAINT ck_NutritionalInfo_NonNegative CHECK (
        CaloriesKcal >= 0
            AND ProteinG >= 0
            AND CarbsG >= 0
            AND FatG >= 0
            AND (FiberG IS NULL OR FiberG >= 0)
            AND (SodiumMg IS NULL OR SodiumMg >= 0)
        );

-- Date range constraints
ALTER TABLE BoxPrice
    ADD CONSTRAINT ck_BoxPrice_DateRange CHECK (
        ValidFrom IS NULL OR ValidTo IS NULL OR ValidFrom <= ValidTo
        );
ALTER TABLE PlatformSubscription
    ADD CONSTRAINT ck_PlatformSubscription_DateRange CHECK (
        ValidFrom IS NULL OR ValidTo IS NULL OR ValidFrom <= ValidTo
        );
